version: '3.8'

services:
  video-generator:
    build: .
    container_name: video-generator
    environment:
      - API_URL=http://localhost:3100/api/generate-video
      - RSYNC_SOURCE=./data/output
      - RSYNC_DEST=root@112.126.78.105:~/web/x
      - SSH_KEY_PATH=/root/.ssh/id_rsa
      - SCHEDULE_TIME=14:00
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ~/.ssh:/root/.ssh:ro
      - ./data:/app/data
    networks:
      - video-gen-network
    restart: unless-stopped
    # 默认启动调度器模式
    command: python video_generator.py

  # 一次性执行服务
  video-generator-once:
    build: .
    container_name: video-generator-once
    environment:
      - API_URL=http://localhost:3100/api/generate-video
      - RSYNC_SOURCE=./data/output
      - RSYNC_DEST=root@112.126.78.105:~/web/x
      - SSH_KEY_PATH=/root/.ssh/id_rsa
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ~/.ssh:/root/.ssh:ro
      - ./data:/app/data
    networks:
      - video-gen-network
    restart: "no"
    # 立即执行一次
    command: python video_generator.py --run-once
    profiles:
      - manual

networks:
  video-gen-network:
    driver: bridge